task: task2
video: Data/AICity_data/train/S03/c010/vdo.avi
annotations: Data/AICity_data/train/S03/c010/ai_challenge_s03_c010-full_annotation.xml

alpha: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
rho: [0.1]

gif: true