task: task1
video: Data/AICity_data/train/S03/c010/vdo.avi
annotations: Data/AICity_data/train/S03/c010/ai_challenge_s03_c010-full_annotation.xml

alpha: [2.0, 3.0, 4.0]
min_area: [1500, 2000, 2500]
open_size: [1, 3, 5]
close_size: [5, 7, 9]

gif: true