name: c6
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - binutils=2.44=h4852527_5
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.6=hb03c661_0
  - c-compiler=1.11.0=h4d9bdce_0
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cmake=4.2.3=hc85cc9f_1
  - compilers=1.11.0=ha770c72_0
  - conda-gcc-specs=14.3.0=he8ccf15_18
  - cxx-compiler=1.11.0=hfcd1e18_0
  - expat=2.7.4=h7354ed3_0
  - fortran-compiler=1.11.0=h9bea470_0
  - gcc=14.3.0=h76bdaa0_7
  - gcc_impl_linux-64=14.3.0=hd9e9e21_7
  - gcc_linux-64=14.3.0=h298d278_21
  - gfortran=14.3.0=he448592_7
  - gfortran_impl_linux-64=14.3.0=h1a219da_18
  - gfortran_linux-64=14.3.0=hfa02b96_21
  - gifsicle=1.96=hb9d3cd8_0
  - gxx=14.3.0=he448592_7
  - gxx_impl_linux-64=14.3.0=he663afc_7
  - gxx_linux-64=14.3.0=h033eb0a_21
  - kernel-headers_linux-64=4.18.0=he073ed8_9
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.22.2=ha1258a1_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libcurl=8.18.0=hcf29cc6_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=14.3.0=h85bb3a7_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=h68bc16d_18
  - libgomp=15.2.0=h4751f2c_7
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.0=h5eee18b_0
  - libsanitizer=14.3.0=hd08acf3_7
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=14.3.0=h85bb3a7_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.51.0=hb03c661_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - make=4.4.1=hb9d3cd8_2
  - ncurses=6.5=h7934f7d_0
  - ninja=1.13.2=h171cf75_0
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py312h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pkg-config=0.29.2=h4bc722e_1009
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=80.10.2=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64=2.28=h4ee821c_9
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - executing==2.2.1
      - fonttools==4.61.1
      - imageio==2.37.2
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - lxml==6.0.2
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - numpy==2.4.2
      - nvidia-ml-py==13.590.48
      - nvitop==1.6.2
      - opencv-contrib-python==4.13.0.92
      - opencv-python==4.13.0.92
      - pandas==3.0.1
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==12.1.1
      - platformdirs==4.9.2
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.11
      - pygifsicle==1.1.0
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - wcwidth==0.6.0
prefix: /ghome/group02/miniconda3/envs/c6
