name: c6
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py312h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - asttokens==3.0.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - executing==2.2.1
      - fonttools==4.61.1
      - imageio==2.37.2
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jupyter-client==8.8.0
      - jupyter-core==5.9.1
      - kiwisolver==1.4.9
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - nest-asyncio==1.6.0
      - numpy==2.4.2
      - nvidia-ml-py==13.590.48
      - nvitop==1.6.2
      - opencv-python==4.13.0.92
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==12.1.1
      - platformdirs==4.9.2
      - prompt-toolkit==3.0.52
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycocotools==2.0.11
      - pygments==2.19.2
      - pyparsing==3.3.2
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - six==1.17.0
      - stack-data==0.6.3
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - wcwidth==0.6.0
prefix: /ghome/group02/miniconda3/envs/c6
